 
 /*------------------------------------------------------------------------
    File        : IResourceRouter
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : bronco
    Created     : Mon Mar 25 12:50:50 CET 2024
    Notes       : 
  ----------------------------------------------------------------------*/

block-level on error undo, throw.

class okelib.pas.webhandlers.router.IRouter: 
  
  
  
end class.