
/*------------------------------------------------------------------------
    File        : IDefaultContentType
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : bronco
    Created     : Mon May 06 13:22:36 CEST 2024
    Notes       : 
  ----------------------------------------------------------------------*/

interface fwebh.pas.data.IDefaultContentType:  
  
  method public char GetDefaultContentType().
    
end interface.
