
/*------------------------------------------------------------------------
    File        : IRequestData
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : bronco
    Created     : Thu Mar 14 14:49:23 CET 2024
    Notes       : 
  ----------------------------------------------------------------------*/


interface fwebh.pas.data.IRequestData:  
  
  define public property MimeType as char no-undo get. set.
  
end interface.
