/*------------------------------------------------------------------------
    File        : ResponseDataType
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : Richard Kelters / Flusso B.V.
    Created     : Mon Apr 15 15:51:25 CEST 2024
    Notes       : 
  ----------------------------------------------------------------------*/

enum fwebh.pas.data.ResponseDataType :  

  define enum 
    DATASET
    TEMP-TABLE
    BUFFER
    JSON
    MEMPTR
    WIDGET-HANDLE
    .
end enum.