
 /*------------------------------------------------------------------------
    File        : IRouter
    Purpose     : 
    Syntax      : 
    Author(s)   : bronco
    Created     : Tue Mar 26 07:39:15 +01:00 2024
    Notes       : 
  ----------------------------------------------------------------------*/

using okelib.pas.webhandlers.router.Route.

interface okelib.pas.router.IRouter:

    method public Route GetRoute(name as char).

end interface.  // IRouter
