 
 /*------------------------------------------------------------------------
    File        : EmptyService
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : bronco
    Created     : Fri Apr 12 13:52:36 CEST 2024
    Notes       : 
  ----------------------------------------------------------------------*/

block-level on error undo, throw.

class test.pas.service.EmptyService: 

end class.