version: '3.8'

services:

  devcontainer:
    image: docker.io/devbfvio/openedge-devcontainer:12.8.1-rc1
    volumes:
      - ../..:/workspaces:cached
      - ${LICENSE_FILE}:/usr/dlc/progress.cfg
    ports:
      - 3099:3099
    command: sleep infinity
  
  plantuml:
    image: plantuml/plantuml-server
    ports:
      - 8080:8080

  pas:
    image: ${PAS_IMAGE}
    volumes:
      - ${LICENSE_FILE}:/usr/dlc/progress.cfg
      - ../src:/app/src
    ports:
      - ${PAS_PORT}:8810
    environment:
      - PASWEBHANDLERS=/app/src/fwebh/pas/webhandlers/ROOT.handlers
    command:
      - /app/pas/start.sh

    