@startuml
class ResourceDescriptor {
    Resource : string
    Id: string
    ParentResource: string
    ParentResourceId: string
    Verbs: HttpVerbs
}

interface IResourceResolver {
    GetResource(request: IWebRequest) : ResourceDescriptor
}

enum HttpVerbs <<flag>>{
    GET,
    POST,
    PUT,
    DELETE,
    PATCH
}
@enduml