
 /*------------------------------------------------------------------------
    File        : IConfigurable
    Purpose     : 
    Syntax      : 
    Author(s)   : bronco
    Created     : Mon Mar 10 07:23:35 +01:00 2025
    Notes       : 
  ----------------------------------------------------------------------*/

using Progress.Json.ObjectModel.JsonObject.

interface fwebh.core.IConfigurable:

  method public void Configure(config as JsonObject).

end interface.  // IConfigurable
