
/*------------------------------------------------------------------------
    File        : VerbsEnum
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : bronco
    Created     : Mon Mar 25 13:04:11 CET 2024
    Notes       : 
  ----------------------------------------------------------------------*/

enum okelib.pas.webhandlers.HTTPVerbsEnum flags :  

  define enum 
    POST = 1
    GET = 2
    PUT = 4
    DELETE = 8
    PATH = 16
    .    

end enum.
