
/*------------------------------------------------------------------------
    File        : HTTPVerbs
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : bronco
    Created     : Mon Mar 25 13:04:11 CET 2024
    Notes       : 
  ----------------------------------------------------------------------*/

enum fwebh.net.HTTPVerbs flags :  

  define enum 
    GET = 1
    POST = 2 
    PUT = 4
    DELETE = 8 
    PATCH = 16
    .    

end enum.  // HTTPVerbs
