name: Tester for Build workflow

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
        description: 'OpenEdge version to use'
        default: '12.8.2'
      execute_unittests:
        type: boolean
        description: 'Execute unit tests'
        default: true

jobs:

  build:
    uses: ./.github/workflows/build.yaml
    with:
      version: ${{ inputs.version }}
      execute_unittests: ${{ inputs.execute_unittests }}
      evaluate_unittests: ${{ inputs.execute_unittests }}
    secrets: inherit
        
