name: Test Build workflow

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        description: 'OpenEdge version to use'
        default: '12.8.2'

jobs:

  build:
    uses: ./.github/workflows/build.yaml
    with:
      version: ${{ github.event.inputs.version }}
    secrets: inherit

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
 
      - name: results
        run: |
          ls -l ${PWD}/
          ls -l ${PWD}/artifacts/
  

