name: Test Build workflow

on:
  workflow_dispatch:

jobs:

  build:
    strategy:
      fail-fast: false
      matrix:
        version: [ '12.8.1', '12.8.2']
    uses: ./.github/workflows/build.yaml
    with:
      version: ${{ matrix.version }}
      execute_unittests: true
      build_artifacts_name: 'build-artifacts-${{ matrix.version }}.${{ github.run_number }}'
    secrets: inherit

  unittest:
    needs: build
    strategy:
      fail-fast: false
      matrix:
        version: [ '12.8.1', '12.8.2']
    uses: ./.github/workflows/unittest.yaml
    with:
      build_artifacts_name: 'build-artifacts-${{ matrix.version }}.${{ github.run_number }}'

  integrationtest:
    needs: build
    strategy:
      fail-fast: false
      matrix:
        version: [ '12.8.1', '12.8.2']
    runs-on: ubuntu-latest
    steps:
      - name: Display version
        run: |
          echo "Version: ${{ matrix.version }}"
    
