name: Wait test

on: [ push ]

jobs:

  wait_for_ci:
    runs-on: ubuntu-latest
    steps:

      - name: Wait for CI to finish
        run: echo "waiting for ${{ github.ref }} to finish CI"
      
      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.ref }}
          check-name: 'Test passed'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 30   

      - name: CI finished
        run: echo "CI finished"

  after_ci:
    runs-on: ubuntu-latest
    needs: wait_for_ci
    steps:
      - name: Wait for CI to finish
        run: echo "CI finished; executed next steps"
        